version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: app
      MYSQL_PASSWORD: XXXXXXADASDASDASDASD112233##